(() => {
  'use strict';
  const P='p2026v2_', TODAY=()=>new Date().toLocaleDateString('sv-SE'), $=id=>document.getElementById(id), $$=s=>[...document.querySelectorAll(s)];
  const parse=(v,f)=>{if(v==null)return f;try{const x=JSON.parse(v);return x==null?f:x}catch{return f}}, n=(v,f=0)=>Number.isFinite(+v)?+v:f, fmt=(v,d=0)=>n(v).toLocaleString('nb-NO',{minimumFractionDigits:d,maximumFractionDigits:d});
  const defaults={weekdayMin:1800,weekdayMax:2100,weekendMin:2400,weekendMax:2800,footballCalories:2100,proteinMin:150,proteinMax:170,goalWeight:87.5,baselineWeight:94.3,waterTarget:2,sleepTarget:7};
  const presets=[['Brødlunsj',700,52,'4 skiver, skinke og Norvegia'],['Proteinshake',120,24,'ON Whey, 1 scoop'],['¼ cookie dough',230,20,'Proteinvariant'],['Sesame chicken',800,58,'½ oppskrift']];
  const phases={
    phase1:{name:'Fase 1 – Oppbygging',w:{W1:['Overkropp','Teknikk og skulderkontroll',[['Sittende roing','3 × 10'],['Benkpress / pushups','3 × 8'],['Arnold press','3 × 10'],['Enarms roing','3 × 12'],['Incline DB press','3 × 10']]],W2:['Underkropp + akilles','Rolig oppbygging',[['Goblet squat','3 × 10'],['Rumensk markløft','3 × 10'],['Hip thrust','3 × 10'],['Step-ups','3 × 10'],['Leg curl','3 × 12']]],W3:['Fullkropp','Kontrollert belastning',[['Nedtrekk / pullups','3 × 8'],['Benpress','3 × 10'],['Skulderpress','3 × 10'],['KB deadlift','3 × 12'],['Pallof press','3 × 12'],['Planke','3 × 45 sek']]],W4:['Stabilitet','Robusthet og buffer',[['Bulgarsk split squat','3 × 8'],['Landmine press','3 × 8'],['Kabelroing','3 × 12'],['Hamstring curl','3 × 10'],['Farmers carry','2 × 40 m']]]}},
    phase2:{name:'Fase 2 – Fotballklar',w:{W1:['Styrke A – overkropp','Fast mandagsøkt. Hold 1–2 reps i reserve.',[['Sittende roing','3 × 8–10'],['Benkpress','3 × 6–8'],['Nedtrekk','3 × 8–10'],['Arnoldpress / manualpress','2 × 8–10'],['Incline manualpress','2 × 8–10'],['Face pulls','2 × 12–15'],['Hammer curl','2 × 10–15'],['Tricepspress','2 × 10–15']]],W2:['Styrke B – fullkropp','Fast torsdagsøkt. Akilles styrer belastningen på beindelen.',[['Benpress / goblet squat med hælløft','3 × 8–10'],['Rumensk markløft','3 × 8'],['Hip thrust','3 × 8–10'],['Leg curl','2 × 10–12'],['Enarms roing','2 × 10'],['Pallof press','2 × 12 per side'],['Soleus-/tåhev','2–3 × 10–12']]]}},
    phase3:{name:'Fase 3 – Estetikk',w:{W1:['Overkropp A','Bryst, rygg og skuldre',[['Benkpress','4 × 6–8'],['Nedtrekk','4 × 8–10'],['Incline DB press','3 × 10'],['Sittende roing','3 × 10'],['Sidehev','4 × 12–15'],['Bicepscurl','3 × 10–12'],['Tricepspress','3 × 10–12']]],W2:['Underkropp','Behold bein og bakside',[['Front/goblet squat','4 × 6–8'],['Rumensk markløft','4 × 8'],['Hip thrust','3 × 8–10'],['Leg curl','3 × 10–12'],['Step-ups','3 × 8']]],W3:['Overkropp B','Rygg, øvre bryst og armer',[['Enarms roing','4 × 8–10'],['Incline brystpress','4 × 8–10'],['Landmine press','3 × 8–10'],['Nøytralt nedtrekk','3 × 10'],['Bakside skulder','3 × 12–15'],['Hammercurl','3 × 10–12']]],W4:['Robusthet','Lett helkropp og prehab',[['Split squat','3 × 8'],['Kabelroing','3 × 12'],['Pushups','3 sett'],['Farmers carry','3 × 30 m'],['Pallof press','3 × 12']]]}}
  };
  const alts={REST:['Hvile / mobilitet','Rolig aktivitet og mobilitet',[]],FOOTBALL:['Fotball','Logg varighet og akillesreaksjon',[]],CARDIO:['Kondisjon','Rolig til moderat etter dagsform',[]],OTHER:['Annen styrke','Beskriv økten i notatfeltet',[]],MOBILITY:['Mobilitet','12–15 minutter er nok',[]]};
  const get=(k,f)=>parse(localStorage.getItem(P+k),f), set=(k,v)=>localStorage.setItem(P+k,JSON.stringify(v));
  const settings=()=>({...defaults,...get('settings',{})});
  const newDay=()=>({date:TODAY(),calories:0,protein:0,water:0,sleep:0,meals:[],habits:{movement:false,mobility:false,creatine:false,structured:false},done:false,score:0,training:{phase:get('phase','phase2'),workoutKey:'W1',energy:3,achilles:0,ankle:0,back:0,note:'',completed:false,entries:{}}});
  let day=get('day_'+TODAY(),newDay()), toastTimer, deferred;
  const saveDay=()=>set('day_'+TODAY(),day);
  const range=()=>{const s=settings(),d=new Date().getDay(),football=day.training.workoutKey==='FOOTBALL';return football?[s.footballCalories,s.footballCalories]:([0,5,6].includes(d)?[s.weekendMin,s.weekendMax]:[s.weekdayMin,s.weekdayMax])};
  const score=()=>{const s=settings(),r=range();let x=0;if(day.calories>=r[0]&&day.calories<=r[1]+150)x+=30;else if(day.calories>0)x+=15;if(day.protein>=s.proteinMin)x+=25;else if(day.protein>=120)x+=15;if(day.water>=s.waterTarget)x+=10;if(day.sleep>=s.sleepTarget)x+=10;if(day.habits.movement||day.training.completed)x+=10;if(day.habits.mobility)x+=5;if(day.habits.creatine)x+=5;if(day.habits.structured)x+=5;return Math.min(100,x)};
  function toast(t){const e=$('toast');e.textContent=t;e.classList.add('is-visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('is-visible'),2200)}
  function nav(v){$$('.view').forEach(e=>e.classList.toggle('is-active',e.dataset.view===v));$$('[data-nav]').forEach(e=>e.classList.toggle('is-active',e.dataset.nav===v));scrollTo({top:0,behavior:'smooth'});if(v==='progress')setTimeout(chart,60)}
  function renderToday(){const s=settings(),r=range(),w=get('weights',[]),last=w.at(-1)?.weight||s.baselineWeight,remain=Math.max(0,last-s.goalWeight),pct=Math.max(0,Math.min(100,(s.baselineWeight-last)/(s.baselineWeight-s.goalWeight)*100));
    $('todayDate').textContent=new Date().toLocaleDateString('nb-NO',{weekday:'long',day:'numeric',month:'long'});$('calorieTarget').textContent=r[0]===r[1]?fmt(r[0]):`${fmt(r[0])}–${fmt(r[1])}`;$('proteinTarget').textContent=`${s.proteinMin}–${s.proteinMax}`;$('currentWeight').textContent=fmt(last,1);$('goalWeight').textContent=fmt(s.goalWeight,1);$('goalRingValue').textContent=`${fmt(remain,1)} kg`;$('goalRing').style.setProperty('--ring',`${pct}%`);
    [['caloriesInput','calories'],['proteinInput','protein'],['waterInput','water'],['sleepInput','sleep']].forEach(([id,k])=>$(id).value=day[k]||'');$$('.habit-toggle').forEach(b=>b.classList.toggle('is-active',!!day.habits[b.dataset.habit]));const sc=score();$('dailyScore').textContent=sc;$('dailyScoreBar').style.width=sc+'%';$('scoreMessage').textContent=sc>=70?'Godkjent dag. Dette er akkurat det som bygger resultatet.':'70 poeng holder streaken i live – prioriter kalorier og protein.';
    const st=get('streak',{current:0,best:0});$('currentStreak').textContent=st.current;$('bestStreak').textContent=st.best;const wk=currentWorkout();$('todayWorkoutTitle').textContent=wk[0];$('todayWorkoutNote').textContent=`${phases[day.training.phase]?.name||''}. ${wk[1]}`;nextAction();}
  function nextAction(){const s=settings(),r=range(),t=$('nextActionDot');t.className='status-dot';let title='Hold planen enkel',text='Start med å logge kalorier og protein. Resten er bonus.';if(day.protein<s.proteinMin){title='Protein først';text=`Du mangler omtrent ${Math.max(0,s.proteinMin-day.protein)} g til minimumsmålet.`}else if(day.calories<r[0]){title='Du har fortsatt rom';text=`Omtrent ${r[0]-day.calories} kcal igjen til nedre del av dagens ramme.`}else if(day.calories<=r[1]){title='Midt i planen';text='Ikke jag perfeksjon. Hold resten av kvelden ryddig.';t.classList.add('good')}else{title='Brems småspisingen';text='Dagens ramme er passert. Ingen straff – bare avslutt strukturert.';t.classList.add('alert')}$('nextActionTitle').textContent=title;$('nextActionText').textContent=text}
  function mealButton(p){return `<button class="preset-button" data-preset="${p[0]}"><strong>${p[0]}</strong><span>${p[1]} kcal · ${p[2]} g protein</span><small>${p[3]}</small></button>`}
  function renderMeals(){const s=settings(),r=range();$('quickMealPresets').innerHTML=presets.map(mealButton).join('');$('mealPresets').innerHTML=presets.map(mealButton).join('');$$('[data-preset]').forEach(b=>b.onclick=()=>{const p=presets.find(x=>x[0]===b.dataset.preset);addMeal(...p.slice(0,3))});$('nutritionCalories').textContent=fmt(day.calories);$('nutritionProtein').textContent=fmt(day.protein);$('calorieProgressBar').style.width=Math.min(100,day.calories/r[1]*100)+'%';$('proteinProgressBar').style.width=Math.min(100,day.protein/s.proteinMin*100)+'%';$('calorieProgressText').textContent=`${fmt(day.calories)} av ${fmt(r[0])}–${fmt(r[1])} kcal`;$('proteinProgressText').textContent=`${fmt(day.protein)} av ${s.proteinMin}–${s.proteinMax} g`;
    $('mealLog').className='list-stack'+(day.meals.length?'':' empty-state');$('mealLog').innerHTML=day.meals.length?day.meals.map((m,i)=>`<div class="list-row"><div class="list-row-main"><strong>${m.name}</strong><small>${m.kcal} kcal · ${m.protein} g protein</small></div><button class="remove-button" data-remove="${i}">×</button></div>`).join(''):'Ingen måltider logget ennå.';$$('[data-remove]').forEach(b=>b.onclick=()=>{const m=day.meals.splice(+b.dataset.remove,1)[0];day.calories=Math.max(0,day.calories-m.kcal);day.protein=Math.max(0,day.protein-m.protein);saveDay();renderAll()})}
  function addMeal(name,kcal,protein){day.meals.push({name,kcal:n(kcal),protein:n(protein),at:new Date().toISOString()});day.calories+=n(kcal);day.protein+=n(protein);saveDay();renderAll();toast(`${name} lagt til`)}
  function currentWorkout(){return phases[day.training.phase]?.w[day.training.workoutKey]||alts[day.training.workoutKey]||phases.phase2.w.W1}
  function renderTraining(){const p=phases[day.training.phase]||phases.phase2;if(!p.w[day.training.workoutKey]&&!alts[day.training.workoutKey])day.training.workoutKey='W1';$('phaseSelect').value=day.training.phase;$('trainingHeading').previousElementSibling.textContent=p.name;const opts=[...Object.keys(p.w),...Object.keys(alts)];$('workoutSelect').innerHTML=opts.map(k=>`<option value="${k}">${(p.w[k]||alts[k])[0]}</option>`).join('');$('workoutSelect').value=day.training.workoutKey;const w=currentWorkout();$('workoutTag').textContent=w[0];$('workoutTitle').textContent=w[0];$('workoutDescription').textContent=w[1];$('workoutNoteInput').value=day.training.note||'';[['energyRange','energy','energyValue'],['achillesRange','achilles','achillesValue'],['ankleRange','ankle','ankleValue'],['backRange','back','backValue']].forEach(([id,k,v])=>{$(id).value=day.training[k];$(v).textContent=day.training[k]});
    $('exerciseList').innerHTML=w[2].length?w[2].map((e,i)=>{const key=`${day.training.phase}_${day.training.workoutKey}_${i}`,last=get('last_'+key,{}),cur=day.training.entries[key]||{};return `<div class="exercise-card"><div class="exercise-top"><strong>${e[0]}</strong><span>${e[1]}</span></div><div class="exercise-last">Sist: ${last.weight?last.weight+' kg':''} ${last.reps?'/ '+last.reps+' reps':''}</div><div class="exercise-fields"><input data-ex="${key}" data-f="weight" type="number" step="0.5" placeholder="kg" value="${cur.weight||''}"><input data-ex="${key}" data-f="reps" type="number" placeholder="reps" value="${cur.reps||''}"><select data-ex="${key}" data-f="feel"><option value="">Følelse</option><option value="easy" ${cur.feel==='easy'?'selected':''}>🙂 Lett</option><option value="ok" ${cur.feel==='ok'?'selected':''}>😐 Passe</option><option value="hard" ${cur.feel==='hard'?'selected':''}>🙁 Tung</option></select></div></div>`}).join(''):'<div class="empty-state">Bruk notatfeltet til å beskrive økten.</div>';$$('[data-ex]').forEach(e=>e.oninput=()=>{day.training.entries[e.dataset.ex]??={};day.training.entries[e.dataset.ex][e.dataset.f]=e.value;saveDay()});bodyAdvice()}
  function bodyAdvice(){const t=day.training,a=Math.max(t.achilles,t.ankle,t.back),e=$('bodyCheckAdvice');e.className='coach-note';if(a>=6){e.textContent='Rødt lys: bytt til mobilitet eller svært lett aktivitet.';e.classList.add('danger')}else if(a>=3||t.energy<=2){e.textContent='Gult lys: reduser belastning eller volum. Ingen testing av grenser.';e.classList.add('warning')}else e.textContent='Grønt lys: tren med 1–2 reps i reserve.'}
  function completeWorkout(){day.training.completed=true;day.habits.movement=true;Object.entries(day.training.entries).forEach(([k,v])=>{if(v.weight||v.reps||v.feel)set('last_'+k,v)});saveDay();renderAll();toast('Økten er lagret')}
  function completeDay(){const sc=score(),st=get('streak',{current:0,best:0,last:null});if(st.last!==TODAY()){st.current=sc>=70?st.current+1:0;st.best=Math.max(st.best,st.current);st.last=TODAY()}day.done=true;day.score=sc;set('streak',st);saveDay();renderAll();toast(sc>=70?'Dagen er godkjent 🔥':'Dagen er lagret')}
  function renderProgress(){const s=settings(),w=get('weights',[]),last=w.at(-1)?.weight||s.baselineWeight,first=w[0]?.weight||s.baselineWeight,avg=w.slice(-7).reduce((a,x)=>a+x.weight,0)/(w.slice(-7).length||1);$('progressCurrentWeight').textContent=fmt(last,1);$('weightChange').textContent=(last-first>0?'+':'')+fmt(last-first,1);$('weightAverage').textContent=fmt(avg,1);$('weightRemaining').textContent=fmt(Math.max(0,last-s.goalWeight),1);$('weightHistory').className='list-stack'+(w.length?'':' empty-state');$('weightHistory').innerHTML=w.length?[...w].reverse().slice(0,12).map(x=>`<div class="list-row"><div><strong>${fmt(x.weight,1)} kg${x.waist?' · '+fmt(x.waist,1)+' cm':''}</strong><small>${x.date}${x.note?' · '+x.note:''}</small></div></div>`).join(''):'Ingen målinger registrert.';chart()}
  function chart(){const c=$('weightChart'),w=get('weights',[]).slice(-30),card=c.closest('.chart-card');card.classList.toggle('is-empty',w.length<2);if(w.length<2)return;const ctx=c.getContext('2d'),dpr=devicePixelRatio||1,width=c.clientWidth||680,height=300;c.width=width*dpr;c.height=height*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,width,height);const vals=w.map(x=>x.weight),min=Math.min(...vals)-.5,max=Math.max(...vals)+.5,p=25,x=i=>p+i*(width-2*p)/(w.length-1),y=v=>p+(max-v)*(height-2*p)/(max-min);ctx.strokeStyle='rgba(255,255,255,.1)';ctx.lineWidth=1;for(let i=0;i<4;i++){const yy=p+i*(height-2*p)/3;ctx.beginPath();ctx.moveTo(p,yy);ctx.lineTo(width-p,yy);ctx.stroke()}ctx.strokeStyle='#7cf2b0';ctx.lineWidth=3;ctx.beginPath();w.forEach((v,i)=>i?ctx.lineTo(x(i),y(v.weight)):ctx.moveTo(x(i),y(v.weight)));ctx.stroke();ctx.fillStyle='#7cf2b0';w.forEach((v,i)=>{ctx.beginPath();ctx.arc(x(i),y(v.weight),4,0,Math.PI*2);ctx.fill()})}
  function renderSettings(){const s=settings();[['weekdayMinInput','weekdayMin'],['weekdayMaxInput','weekdayMax'],['weekendMinInput','weekendMin'],['weekendMaxInput','weekendMax'],['proteinMinInput','proteinMin'],['proteinMaxInput','proteinMax'],['goalWeightInput','goalWeight'],['footballCaloriesInput','footballCalories']].forEach(([id,k])=>$(id).value=s[k]);const p=('Notification'in window)?Notification.permission:'unsupported';$('notificationStatus').textContent=p==='granted'?'Nettvarsler er tillatt.':p==='unsupported'?'Nettvarsler støttes ikke her. Bruk kalenderpåminnelsene.':'Ingen varsler aktivert.'}
  function renderAll(){renderToday();renderMeals();renderTraining();renderProgress();renderSettings()}
  function bind(){$$('[data-nav]').forEach(b=>b.onclick=()=>nav(b.dataset.nav));$$('[data-go]').forEach(b=>b.onclick=()=>nav(b.dataset.go));[['caloriesInput','calories'],['proteinInput','protein'],['waterInput','water'],['sleepInput','sleep']].forEach(([id,k])=>$(id).oninput=e=>{day[k]=n(e.target.value);saveDay();renderToday();renderMeals()});$$('.habit-toggle').forEach(b=>b.onclick=()=>{day.habits[b.dataset.habit]=!day.habits[b.dataset.habit];saveDay();renderToday()});$('completeDayBtn').onclick=completeDay;
    $('customMealForm').onsubmit=e=>{e.preventDefault();addMeal($('mealNameInput').value,n($('mealCaloriesInput').value),n($('mealProteinInput').value));e.target.reset()};$('clearMealsBtn').onclick=()=>{if(confirm('Tømme dagens måltidslogg?')){day.meals=[];day.calories=day.protein=0;saveDay();renderAll()}};$('phaseSelect').onchange=e=>{day.training.phase=e.target.value;day.training.workoutKey='W1';set('phase',e.target.value);saveDay();renderAll()};$('workoutSelect').onchange=e=>{day.training.workoutKey=e.target.value;day.training.completed=false;saveDay();renderAll()};[['energyRange','energy'],['achillesRange','achilles'],['ankleRange','ankle'],['backRange','back']].forEach(([id,k])=>$(id).oninput=e=>{day.training[k]=n(e.target.value);saveDay();renderTraining()});$('workoutNoteInput').oninput=e=>{day.training.note=e.target.value;saveDay()};$('completeWorkoutBtn').onclick=completeWorkout;
    $('progressForm').onsubmit=e=>{e.preventDefault();const w=get('weights',[]),rec={date:TODAY(),weight:n($('progressWeightInput').value),waist:n($('waistInput').value)||null,note:$('progressNoteInput').value.trim()};const i=w.findIndex(x=>x.date===rec.date);i>=0?w[i]=rec:w.push(rec);set('weights',w);e.target.reset();renderAll();toast('Måling lagret')};$('settingsForm').onsubmit=e=>{e.preventDefault();const s=settings();[['weekdayMinInput','weekdayMin'],['weekdayMaxInput','weekdayMax'],['weekendMinInput','weekendMin'],['weekendMaxInput','weekendMax'],['proteinMinInput','proteinMin'],['proteinMaxInput','proteinMax'],['goalWeightInput','goalWeight'],['footballCaloriesInput','footballCalories']].forEach(([id,k])=>s[k]=n($(id).value));set('settings',s);renderAll();toast('Målene er lagret')};
    $('notificationBtn').onclick=async()=>{if(!('Notification'in window))return toast('Nettvarsler støttes ikke her');const p=await Notification.requestPermission();renderSettings();if(p==='granted')new Notification('Prosjekt 2026',{body:'Varsler er aktivert.'})};$('calendarReminderBtn').onclick=calendar;$('exportDataBtn').onclick=()=>download(JSON.stringify(Object.fromEntries(Object.keys(localStorage).filter(k=>k.startsWith(P)).map(k=>[k,localStorage.getItem(k)])),null,2),'prosjekt-2026-backup.json','application/json');$('importDataInput').onchange=async e=>{try{const d=JSON.parse(await e.target.files[0].text());Object.entries(d).forEach(([k,v])=>localStorage.setItem(k,v));location.reload()}catch{toast('Kunne ikke importere backup')}};$('resetDataBtn').onclick=()=>{if(confirm('Slette alle v2-data på denne enheten?')){Object.keys(localStorage).filter(k=>k.startsWith(P)).forEach(k=>localStorage.removeItem(k));location.reload()}};window.onresize=chart;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;$('installAppBtn').hidden=false});$('installAppBtn').onclick=async()=>{if(deferred){deferred.prompt();await deferred.userChoice;deferred=null;$('installAppBtn').hidden=true}}}
  function download(content,name,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
  function calendar(){const d=new Date(),date=d.toISOString().slice(0,10).replaceAll('-',''),ics=`BEGIN:VCALENDAR\r\nVERSION:2.0\r\nBEGIN:VEVENT\r\nDTSTART:${date}T080000\r\nRRULE:FREQ=DAILY\r\nSUMMARY:Prosjekt 2026 – dagens plan\r\nBEGIN:VALARM\r\nTRIGGER:PT0M\r\nACTION:DISPLAY\r\nDESCRIPTION:Sjekk dagens kaloriramme og proteinmål\r\nEND:VALARM\r\nEND:VEVENT\r\nBEGIN:VEVENT\r\nDTSTART:${date}T203000\r\nRRULE:FREQ=DAILY\r\nSUMMARY:Prosjekt 2026 – kveldssjekk\r\nBEGIN:VALARM\r\nTRIGGER:PT0M\r\nACTION:DISPLAY\r\nDESCRIPTION:Logg kalorier og protein\r\nEND:VALARM\r\nEND:VEVENT\r\nEND:VCALENDAR`;download(ics,'prosjekt-2026-paminnelser.ics','text/calendar')}
  document.addEventListener('DOMContentLoaded',()=>{if(!localStorage.getItem(P+'settings'))set('settings',defaults);bind();renderAll();nav(new URLSearchParams(location.search).get('view')||'today');if('serviceWorker'in navigator)navigator.serviceWorker.register('/service-worker.js').catch(console.warn)});
})();
