const {test}=require('node:test'),assert=require('node:assert/strict');
const C=require('../coach-core.js'),{create}=require('../storage.js');
function memory(initial={}){const m=new Map(Object.entries(initial));return{get length(){return m.size;},key:i=>[...m.keys()][i],getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k)};}
const food=(id='f')=>({id,name:'Synthetic test meal',kcal:2000,protein:170,qty:1});
test('v2 normalization retains unknown fields, history, targets and weights',()=>{const old={...C.defaultState(),version:2,custom:'preserve',workouts:[{id:'a',date:'2026-08-01',key:'W1',entries:[{exId:'row',sets:[{weight:0,reps:8}],note:'original'}]}]};delete old.drafts;const n=C.normalizeState(old);assert.equal(n.version,3);assert.deepEqual(n.workouts,old.workouts);assert.equal(n.custom,'preserve');assert.deepEqual(old.version,2);});
test('malformed and future backups rejected before writing',()=>{for(const patch of [{version:99},{foods:[]},{metrics:'bad'},{workouts:[{}]},{settings:{protein:0}}])assert.throws(()=>C.normalizeState({...C.defaultState(),...patch}));});
test('comma decimal parser distinguishes blank and zero',()=>{assert.equal(C.number('2,5'),2.5);assert.equal(C.number(''),null);assert.equal(C.number('0'),0);assert.equal(C.number('NaN'),null);});
test('unknown readiness never green-lights progression; swelling overrides energy',()=>{assert.equal(C.readinessInfo(null).status,'neutral');assert.equal(C.readinessInfo({energy:5,swelling:true}).status,'warn');assert.equal(C.readinessInfo({energy:5,redFlags:true}).status,'bad');assert.equal(C.readinessInfo({energy:5,reaction:'worse'}).status,'warn');});
test('progression requires two full explicit sets histories and tolerable readiness',()=>{const s=C.defaultState(),date='2026-09-09',ex={id:'row',sets:4,repMax:8,weight:true};s.days[date]={readiness:{energy:4,reaction:"same"}};const make=(date)=>({id:date,date,key:'W1',mode:'normal',phase:'phase2',schemaVersion:3,entries:[{exId:'row',sets:Array.from({length:4},()=>({weight:40,reps:8,done:true})),feel:'easy',rir:2}]});s.workouts=[make('2026-08-26'),make('2026-09-02')];assert.equal(C.recommendation(s,ex,date).action,'increase');s.workouts[1].entries[0].sets.pop();assert.notEqual(C.recommendation(s,ex,date).action,'increase');s.workouts[1]=make('2026-09-02');s.workouts[1].mode='minimum';assert.notEqual(C.recommendation(s,ex,date).action,'increase');s.workouts[1]=make('2026-09-02');s.days[date].readiness.swelling=true;assert.notEqual(C.recommendation(s,ex,date).action,'increase');});
test('calorie points require complete nutrition and never reward under-eating',()=>{const s=C.defaultState(),d='2026-09-09';s.days[d]={habits:{},nutritionComplete:false};s.foods[d]=[food()];assert.equal(C.scoreDay(s,d).calories,0);s.days[d].nutritionComplete=true;assert.equal(C.scoreDay(s,d).calories,25);s.foods[d][0].kcal=500;assert.equal(C.scoreDay(s,d).calories,0);});
test('past streak threshold independent of edited current settings',()=>{const s=C.defaultState();s.days['2026-09-08']={completed:true,score:70,targets:{threshold:70}};s.settings.scoreThreshold=90;assert.equal(C.streakStats(s,'2026-09-09').current,1);s.days['2026-09-10']={completed:true,score:100};assert.equal(C.streakStats(s,'2026-09-09').best,1);});
test('weight summary excludes stale measurements and sparse week comparisons',()=>{const s=C.defaultState();s.metrics=[{date:'2026-08-01',weight:95}];assert.equal(C.weightSummary(s,'2026-09-09').average,null);s.metrics.push({date:'2026-09-08',weight:94});assert.equal(C.weightSummary(s,'2026-09-09').average,94);assert.equal(C.weightSummary(s,'2026-09-09').change,null);});
test('merge is additive, idempotent and retains current conflicting entries',()=>{const a=C.defaultState(),b=C.defaultState();a.foods['2026-09-09']=[food('a')];b.foods['2026-09-09']=[food('b')];const m=C.mergeState(a,b);assert.equal(m.foods['2026-09-09'].length,2);assert.deepEqual(C.mergeState(m,b),m);assert.equal(a.foods['2026-09-09'].length,1);});
test('storage never overwrites corrupt originals or silently drops writes',()=>{const m=memory({[C.STORE_KEY]:'{bad'}),r=create(()=>m);r.read();assert(r.blocked);assert.equal(r.save(C.defaultState()),false);assert.equal(m.getItem(C.STORE_KEY),'{bad');const m2=memory(),r2=create(()=>m2);r2.read();m2.setItem=()=>{throw Error('quota');};assert.equal(r2.save(C.defaultState()),false);assert.match(r2.error,/Ikke lagret/);});
test('multi-tab conflict refuses stale overwrite',()=>{const m=memory(),a=create(()=>m),b=create(()=>m);const s=a.read();b.read();a.save(s);assert.equal(b.save(C.defaultState()),false);assert.equal(m.getItem(C.STORE_KEY),JSON.stringify(s));});
test('checkpoint preserves the exact original and replace snapshots current data',()=>{const raw=JSON.stringify({...C.defaultState(),version:2}),m=memory({[C.STORE_KEY]:raw}),r=create(()=>m),s=r.read();assert(r.checkpoint('migration'));r.save(s);assert.equal(JSON.parse(m.getItem(C.STORE_KEY+'_before_v3')).raw,raw);s.metrics.push({date:'2026-09-09',weight:90});assert(r.replace(s));assert(JSON.parse(r.recovery()).raw);});
